"""
Project Euler 45 - Triangular, Pentagonal, and Hexagonal
https://projecteuler.net/problem=45

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle     T_n = n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal   P_n = n(3n-1)/2    1, 5, 12, 22, 35, ...
Hexagonal    H_n = n(2n-1)      1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
from math import isqrt

def is_triangle(n: int) -> bool:
	x = isqrt(2*n)
	return x*(x+1) == 2*n

def is_pentagon(n: int) -> bool:
	x = isqrt(2*n//3) + 1
	return 3*x*x - x == 2*n

def next_triangle_pentagonal_hexagonal(after: int) -> int:
	n = 1
	h = n * (2*n - 1)
	while h <= after:
		n += 1
		h = n * (2*n - 1)
	while not is_triangle(h) or not is_pentagon(h):
		n += 1
		h = n * (2*n - 1)
	return h


# Example: after = 1 -> 40755
print(next_triangle_pentagonal_hexagonal(1))

# Answer
print(next_triangle_pentagonal_hexagonal(40755))
